sudo: required
services:
  - docker

env:
  # multiple env with same key runs a matrix process execution
  - NPM_TARGET=test
  - NPM_TARGET=lint # for checking syntax errors
  - NPM_TARGET=coverage

before_install:
  - docker pull node:8-onbuild

# This helps install requirements needed for the script stage
install:
  - docker build -t probot-hello .

script:
  - docker run --rm probot-hello npm run $NPM_TARGET

after_success:
# We want to provide tag for only test-related sscript
  - set -x -v;
    set -e;
    if [ "$(NPM_TARGET)" = "test" ]; then
      docker tag probot-hello probot-hello:$(git rev-parse HEAD);
    else
      echo "skipping docker tag";
    fi;
    docker images;
    set +x +v;