sudo: required
services:
  - docker

before_install:
  - docker pull node:8-onbuild

# This helps install requirements needed for the script stage
install:
  - docker build -t probot-hello .

script:
  - docker run --rm probot-hello npm run test
  - docker run --rm probot-hello npm run lint # for checking syntax errors